-- Generated by tests/func_typed_expr.py from its corpus; do not edit.
-- Regenerate with "python func_typed_expr.py --write" from the tests directory.
-- The library modules and the twins whose leaves are values of an earlier
-- evaluation.  The REPL of PAKCS refuses a goal whose type names Identity,
-- a type the loaded module does not declare, so the newtype twins reach it
-- through show, runIdentity and ==.
import Data.Functor.Identity
import Data.List
import Data.Maybe

goal_sum = Data.List.sum [1, 2, 3]
goal_sum_floats = Data.List.sum [1.5, 2.5]
goal_maximum = Data.List.maximum [1, 3, 2]
goal_nub = Data.List.nub [1, 1, 2]
goal_frommaybe = Data.Maybe.fromMaybe 0 Nothing
goal_fromjust = Data.Maybe.fromJust (Just 1)
goal_lookup = lookup 1 [(1, 'a')]
goal_elem = elem 2 [1, 2]
goal_zip = zip [1, 2] "ab"
goal_unwords = unwords ["a", "bc"]
goal_concat = concat ["ab", "c"]
goal_identity_run = Data.Functor.Identity.runIdentity (Data.Functor.Identity.Identity 5)
goal_identity_show = show (Data.Functor.Identity.Identity 5)
goal_identity_eq = Data.Functor.Identity.Identity 5 == Data.Functor.Identity.Identity 5
goal_identity_fmap = Data.Functor.Identity.runIdentity (fmap ((+) 1) (Data.Functor.Identity.Identity 5))
goal_identity_apply = Data.Functor.Identity.runIdentity (apply Data.Functor.Identity.Identity 5)
goal_sum_value = sum [1.5, 2.5]
goal_fromjust_value = fromJust (Just 1) + 2
goal_length_value = length "ab"
goal_sum_reverse_value = sum (reverse [1, 2, 3])
goal_fst_value = fst (1, 'a')
goal_show_value = show (Just [1.5])
goal_node_twice = 21 + 21
goal_iterator = take 3 [0 ..]
goal_iterator_sum = sum [1, 2, 3]
