-- Generated by tests/func_typed_expr.py from its corpus; do not edit.
-- Regenerate with "python func_typed_expr.py --write" from the tests directory.
-- Declarations of the module: a newtype, which both systems erase at run
-- time, a data type with a Num instance, a class with two instances, and
-- bindings without signatures, which the front end gives dictionary
-- parameters.

newtype Box a = Box a
  deriving (Eq, Show)

data Nat = Z | S Nat
  deriving (Eq, Show)

instance Num Nat where
  Z + n = n
  S m + n = S (m + n)
  Z * _ = Z
  S m * n = n + m * n
  negate _ = Z
  abs n = n
  signum Z = Z
  signum (S _) = S Z
  fromInt n = if n <= 0 then Z else S (fromInt (n - 1))

twice :: Num a => a -> a
twice x = x + x

natToInt :: Nat -> Int
natToInt Z = 0
natToInt (S n) = 1 + natToInt n

class Pretty a where
  pretty :: a -> String

instance Pretty Bool where
  pretty b = if b then "yes" else "no"

instance Pretty a => Pretty [a] where
  pretty xs = concatMap pretty xs

idf = id
g14 = Just 5
g15 = 1 + 2
addOne x = x + 1

goal_box = Box 5
goal_box_eq = Box 5 == Box 5
goal_box_show = show (Box 5)
goal_box_pair = (Box 1, 'a')
goal_box_list = [Box 1, Box 2]
goal_box_bare = apply Box 5
goal_nat = (twice 2 :: Nat)
goal_nat_literal = (3 :: Nat)
goal_toint = natToInt 3
goal_toint_twice = natToInt (twice 2)
goal_nat_list = [S Z, Z]
goal_pretty = pretty [True, False]
goal_idf = idf 1
goal_g14 = g14
goal_g15 = g15
goal_addone = addOne 1
goal_addone_float = addOne 1.5
goal_twice_int = twice 2
goal_twice_float = twice 1.5
