-- Generated by tests/func_typed_expr.py from its corpus; do not edit.
-- Regenerate with "python func_typed_expr.py --write" from the tests directory.
-- Goals for the type oracle alone: function values, which the PAKCS REPL
-- prints in its own form, types its table rejects, and I/O.
import Data.Maybe

goal_plus_section = (+) 1
goal_plus_bare = (+)
goal_map_not = map not
goal_id = id
goal_const = const 1
goal_compose = not . not
goal_flip_cons = flip (:) []
goal_show = show
goal_fromjust = Data.Maybe.fromJust
goal_maxbound = maxBound
goal_toenum = toEnum 65
goal_read = read "5"
goal_enumfrom = enumFrom 1
goal_return = return 5
goal_pure_pair = pure (1, 'a')
goal_mapm = mapM_ print [1, 2]
goal_free_eq x1 x2 = x1 =:= x2
goal_free_const x1 = const 1 x1
