#!/bin/bash
# Configures Sprite and then invokes the program named by .bin/$0.  This is
# used by creating a link to this script whose name is the name of the program
# to invoke.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT=$( realpath $DIR/.. )
#
dir=$ROOT/lib/python2.7/
test -d $dir || ( echo 2>&1 "Python library not found at \"$dir\"."; exit 1 )
export PYTHONPATH=$dir:$PYTHONPATH
#
dir=$ROOT/lib/
test -d $dir || ( echo 2>&1 "Sprite library not found at \"$dir\"."; exit 1 )
export LD_LIBRARY_PATH=$dir:$LD_LIBRARY_PATH
#
dir=$ROOT/lib/curry
test -d $dir || ( echo 2>&1 "Curry library not found at \"$dir\"."; exit 1 )
export CURRYPATH=$dir:$CURRYPATH
#
exec $DIR/../.bin/$(basename $0) "$@"
