sprite/exec.hpp File Reference
Interface to the execution components.
#include `sprite/builtins.hpp`
#include `sprite/common.hpp`
#include `sprite/fingerprint.hpp`
#include `sprite/node.hpp`
#include `sprite/program.hpp`
#include `sprite/rewrite.hpp`
Namespaces
namespace sprite
Classes
struct sprite::YieldHandler
Base of a class that handles computation results as they are generated.
struct sprite::YieldHandler_< OutputIterator >
A concrete YieldHandler(p.) for a particular output iterator type.
struct sprite::YieldHandler_< void >
A yield handler that simply discards the output.
Enumerations
enum TraceOption { NO_TRACE = false,
TRACE = true
 }
Functions
void execute (Program const &program, Node &goal, TraceOption trace)
template<typename OutputIterator> void execute (Program const &pgm, Node &goal, OutputIterator out, TraceOption trace=NO_TRACE)
Alternate form of execute; results are written to the given iterator.
bool is_norm (Node const &node)
Traverses an expression and returns true if it is found to be in cnf.
void pull_tab (Node &g, NodePtr const &p)
Performs the pull-tab transformation.
void head_normalize (Node &node)
The head-normalizing (H) function from the fair scheme.
void fair_normalize (Fingerprint const &fp, Node &node)
The normalizing (N) function from the fair scheme.
Detailed Description
Interface to the execution components.
Definition in file exec.hpp.
Function Documentation
void head_normalize (Node & node) [inline]
The head-normalizing (H) function from the fair scheme.
This is a generic H function that dispatches to the correct implementation for the given operation.
Definition at line 135 of file exec.hpp.
References sprite::g_program, sprite::Node::id(), sprite::Program::oper, and sprite::Node::tag().
Referenced by sprite::fair_normalize(), and sprite::h_func().
void pull_tab (Node & g, NodePtr const & p) [inline]
Performs the pull-tab transformation.
Parameters:
g The source of the transformation.
p The target of the transformation. Must be a direct descendant of g.
Definition at line 118 of file exec.hpp.
References sprite::Node::clone(), sprite::Node::position(), and sprite::rewrite_choice.
Referenced by sprite::fair_normalize(), and sprite::h_func().