sprite/exec.cpp File Reference
Implements functions related to execution.
#include `sprite/exec.hpp`
#include `sprite/node.hpp`
#include `sprite/operators.hpp`
#include <deque>
Namespaces
namespace sprite
Classes
struct sprite::PoolItem
An item in the computation pool.
struct sprite::ComputationPool
A computation pool.
Functions
void execute (Program const &pgm, Node &goal, YieldHandler const &out, TraceOption trace)
Execute a goal in the context of the given program.
void print_node (Node const &node)
Print an expression.
Variables
Program const * g_program = NULL
Global pointer to the currently executing program.
Detailed Description
Implements functions related to execution.
Definition in file exec.cpp.
Function Documentation
void sprite::execute (Program const & program, Node & goal, YieldHandler const & handler = YieldHandler_< void >(), TraceOption trace = NO_TRACE)
Execute a goal in the context of the given program.
This is the the primary entry point to the execution system. Execution proceeds in-place, meaning that the goal expression will likely be modified.
Parameters:
program The program definition. This provides the necessary information to carry out execution as a series of rewrite steps.
goal The goal statement. Modified in place.
handler (optional) Defaults to a handler that discards the generated results. The object that handles output as it is generated.
trace (optional) Defaults to true. Enables debug tracing.
Definition at line 102 of file exec.cpp.
References sprite::Fingerprint::at(), sprite::fair_normalize(), sprite::g_program, sprite::Fingerprint::has(), sprite::Node::id(), sprite::is_norm(), sprite::Fingerprint::resize(), sprite::Fingerprint::set(), sprite::Fingerprint::size(), sprite::Node::tag(), and sprite::YieldHandler::yield().
void sprite::print_node (Node const &)
Print an expression.
Note: Alias for operator<<, callable from the debugger.
Definition at line 189 of file exec.cpp.