sprite Namespace Reference
The main namespace for sprite.
Classes
struct sprite::RuntimeError
Thrown to indicate a runtime error in the execution system.
struct sprite::PoolItem
An item in the computation pool.
struct sprite::ComputationPool
A computation pool.
struct sprite::YieldHandler
Base of a class that handles computation results as they are generated.
struct sprite::YieldHandler_< OutputIterator >
A concrete YieldHandler(p.) for a particular output iterator type.
struct sprite::YieldHandler_< void >
A yield handler that simply discards the output.
struct sprite::Fingerprint
A fingerprint specification.
struct sprite::Node
An expression node.
struct sprite::Node_< Payload >
A complete node. The payload contains tag-specific data.
struct sprite::NodePtr
A reference-counting pointer for Node(p.) objects.
struct sprite::Program
A program definition.
struct sprite::rewrite< OPER >
Rewrites a node to an OPER node.
struct sprite::rewrite< CTOR >
Rewrites a node to a CTOR node.
struct sprite::rewrite< FAIL >
Rewrites a node to FAIL.
struct sprite::rewrite< CHOICE >
Rewrites a node to CHOICE.
struct sprite::rewrite< FWD >
Rewrites a node to FWD.
struct sprite::rewrite< INT >
Rewrites a node to INT.
struct sprite::rewrite< FLOAT >
Rewrites a node to FLOAT.
struct sprite::Loader
Interface to the module loader.
struct sprite::Module
Interface to a module.
struct sprite::UserModule
A basic implementation of the Module(p.) interface.
Typedefs
typedef boost::uint_t< 32 >::exact uint32
typedef Node_< payloads::Unused<> > AbstractNode
A complete node where the payload is unknown.
typedef Node_< payloads::InPlace< 0 > > InPlaceNode0
A complete node with exactly zero children.
typedef Node_< payloads::InPlace< 1 > > InPlaceNode1
A complete node with exactly one child.
typedef Node_< payloads::InPlace< 2 > > InPlaceNode2
A complete node with exactly two children.
typedef Node_< payloads::ChildList > ChildListNode
A complete node with more than two children.
typedef Node_< payloads::Choice > ChoiceNode
A complete node representing a choice.
typedef Node_< payloads::Fwd > FwdNode
A complete node representing a forward reference.
typedef Node_< payloads::Int > IntNode
A complete node representing an integer.
typedef Node_< payloads::Float > FloatNode
A complete node representing a floating-point value.
typedef tr1::function< void(Node &) h_func_type)
The type of an H function.
Enumerations
enum BuiltinOp {
OP_INT_ADD,
OP_INT_SUB,
OP_INT_MUL,
OP_INT_DIV,
OP_FLOAT_ADD,
OP_FLOAT_SUB,
OP_FLOAT_MUL,
OP_FLOAT_DIV,
OP_END
 }
The built-in operations.
enum TagValue {
FAIL = 0,
OPER,
CHOICE,
FWD,
INT,
FLOAT,
CTOR
 }
Identifies the type of a node. CTOR must be last!
enum TraceOption { NO_TRACE = false,
TRACE = true
 }
Indicates whether tracing is enabled.
enum ChoiceDirection { LEFT = 0,
RIGHT = 1
 }
Functions
template<BuiltinOp Op> void h_func (Node &node)
Implements the H function for a built in operation.
TagValue make_ctor_tag (int i)
Generates a constructor tag.
bool is_ctor (TagValue x)
Indicates whether a tag represents a constructor (built-in or not).
bool is_builtin (TagValue x)
Indicates whether a tag represents a built-in type.
void execute (Program const &pgm, Node &goal, YieldHandler const &out, TraceOption trace)
Execute a goal in the context of the given program.
void print_node (Node const &node)
Print an expression.
void execute (Program const &program, Node &goal, TraceOption trace)
template<typename OutputIterator> void execute (Program const &pgm, Node &goal, OutputIterator out, TraceOption trace=NO_TRACE)
Alternate form of execute; results are written to the given iterator.
bool is_norm (Node const &node)
Traverses an expression and returns true if it is found to be in cnf.
void pull_tab (Node &g, NodePtr const &p)
Performs the pull-tab transformation.
void head_normalize (Node &node)
The head-normalizing (H) function from the fair scheme.
void fair_normalize (Fingerprint const &fp, Node &node)
The normalizing (N) function from the fair scheme.
BOOST_STATIC_ASSERT (sizeof(AbstractNode)==NODE_BYTES)
BOOST_STATIC_ASSERT (sizeof(InPlaceNode0)==NODE_BYTES)
BOOST_STATIC_ASSERT (sizeof(InPlaceNode1)==NODE_BYTES)
BOOST_STATIC_ASSERT (sizeof(InPlaceNode2)==NODE_BYTES)
BOOST_STATIC_ASSERT (sizeof(ChildListNode)==NODE_BYTES)
BOOST_STATIC_ASSERT (sizeof(ChoiceNode)==NODE_BYTES)
BOOST_STATIC_ASSERT (sizeof(FwdNode)==NODE_BYTES)
BOOST_STATIC_ASSERT (sizeof(IntNode)==NODE_BYTES)
BOOST_STATIC_ASSERT (sizeof(FloatNode)==NODE_BYTES)
bool skip_fwd_ref (NodePtr &ptr, Node &ref)
Tells NodePtr(p.) how to skip FWD nodes.
template<typename Visitor> Visitor::result_type visit (Visitor const &visitor, Node const &node)
Unary visitation; calls visitor((Type)(node)).
template<typename Visitor> Visitor::result_type visit (Visitor const &visitor, Node &node)
Non-const form of visitation.
template<typename Visitor> Visitor::result_type visit (Visitor const &visitor, Node const &lhs, Node const &rhs)
Binary visitation; calls visitor((TypeLhs)(lhs), (TypeRhs)(rhs)).
template<typename Visitor> Visitor::result_type visit (Visitor const &visitor, Node &lhs, Node &rhs)
Non-const form of binary visitation.
Variables
h_func_type builtin_h [OP_END]
The table of built-in H routines.
std::string builtin_oper [OP_END] = { `+`, `-`, `*`, `/`, `+`, `-`, `*`, `/` }
The tables of built-in operation labels.
boost::object_pool< AbstractNode > node_allocator
Global memory pool for allocating nodes.
Program const * g_program = NULL
Global pointer to the currently executing program.
size_t const NODE_BYTES = 32
The size of a complete node.
rewrite< CTOR > const rewrite_ctor = rewrite<CTOR>()
Rewrites a node to type CTOR.
rewrite< OPER > const rewrite_oper = rewrite<OPER>()
Rewrites a node to type OPER.
rewrite< FAIL > const rewrite_fail = rewrite<FAIL>()
Rewrites a node to type FAIL.
rewrite< CHOICE > const rewrite_choice = rewrite<CHOICE>()
Rewrites a node to type CHOICE.
rewrite< FWD > const rewrite_fwd = rewrite<FWD>()
Rewrites a node to type FWD.
rewrite< INT > const rewrite_int = rewrite<INT>()
Rewrites a node to type INT.
rewrite< FLOAT > const rewrite_float = rewrite<FLOAT>()
Rewrites a node to type FLOAT.
Detailed Description
The main namespace for sprite.
Typedef Documentation
typedef Node_<payloads::Fwd> sprite::FwdNode
A complete node representing a forward reference.
This is simply a node that refers to another, which sometimes comes up during rewriting.
Definition at line 262 of file node.hpp.
Enumeration Type Documentation
enum TagValue
Identifies the type of a node. CTOR must be last!
The constructors for any type are assigned the sequential tags CTOR, CTOR+1, CTOR+2,... Said another way, this type is abused in that any value >= CTOR can be a valid TagValue.
Definition at line 66 of file common.hpp.
Referenced by make_ctor_tag(), and sprite::Node::tag().
Function Documentation
void sprite::execute (Program const & program, Node & goal, YieldHandler const & handler = YieldHandler_< void >(), TraceOption trace = NO_TRACE)
Execute a goal in the context of the given program.
This is the the primary entry point to the execution system. Execution proceeds in-place, meaning that the goal expression will likely be modified.
Parameters:
program The program definition. This provides the necessary information to carry out execution as a series of rewrite steps.
goal The goal statement. Modified in place.
handler (optional) Defaults to a handler that discards the generated results. The object that handles output as it is generated.
trace (optional) Defaults to true. Enables debug tracing.
Definition at line 102 of file exec.cpp.
References sprite::Fingerprint::at(), fair_normalize(), g_program, sprite::Fingerprint::has(), sprite::Node::id(), is_norm(), sprite::Fingerprint::resize(), sprite::Fingerprint::set(), sprite::Fingerprint::size(), sprite::Node::tag(), and sprite::YieldHandler::yield().
void head_normalize (Node & node) [inline]
The head-normalizing (H) function from the fair scheme.
This is a generic H function that dispatches to the correct implementation for the given operation. The H.6 rule, which ignors constructor-rooted expressions, is implemented here so that user-compiled H rules can ignore it.
Definition at line 139 of file exec.hpp.
References g_program, sprite::Node::id(), sprite::Program::oper, and sprite::Node::tag().
Referenced by fair_normalize(), and h_func().
void sprite::print_node (Node const &)
Print an expression.
Note: Alias for operator<<, callable from the debugger.
Definition at line 190 of file exec.cpp.
void pull_tab (Node & g, NodePtr const & p) [inline]
Performs the pull-tab transformation.
Parameters:
g The source of the transformation.
p The target of the transformation. Must be a direct descendant of g.
Definition at line 120 of file exec.hpp.
References sprite::Node::clone(), sprite::Node::position(), and rewrite_choice.
Referenced by fair_normalize(), and h_func().
template<typename Visitor> Visitor::result_type visit (Visitor const & visitor, Node const & lhs, Node const & rhs) [inline]
Binary visitation; calls visitor((TypeLhs)(lhs), (TypeRhs)(rhs)).
Determines the type of each node, then calls the visitor with both nodes cast to those types.
Rather than support all four possible overloads related to the const qualifier on Node(p.) arguments, just support the cases where both are qualified or neither one is.
Definition at line 142 of file visit.hpp.
template<typename Visitor> Visitor::result_type visit (Visitor const & visitor, Node const & node) [inline]
Unary visitation; calls visitor((Type)(node)).
Determines the type of the node, based on its tag and arity, then calls the visitor with the node cast to that type.
Definition at line 18 of file visit.hpp.
References sprite::Node::arity(), and sprite::Node::tag().
Referenced by sprite::Node::clone(), sprite::Node::iter(), sprite::Node::operator[](), and sprite::Node::position().
Variable Documentation
h_func_type sprite::builtin_h
Initial value:
  {
      &h_func<OP_INT_ADD>
    , &h_func<OP_INT_SUB>
    , &h_func<OP_INT_MUL>
    , &h_func<OP_INT_DIV>
    , &h_func<OP_FLOAT_ADD>
    , &h_func<OP_FLOAT_SUB>
    , &h_func<OP_FLOAT_MUL>
    , &h_func<OP_FLOAT_DIV>
  }
The table of built-in H routines.
Definition at line 189 of file builtins.cpp.
size_t const sprite::NODE_BYTES = 32
The size of a complete node.
Constrining every complete node type to have the same size simplifies memory pooling and rewriting.
Definition at line 228 of file node.hpp.