sprite::rewrite< CTOR > Struct Template Reference
Rewrites a node to a CTOR node.
#include <rewrite.hpp>
Public Member Functions
rewrite ()
template<typename Enum> void operator() (Node &node, Enum tag, size_t id, size_t arity, NodePtr *args) const
Detailed Description
template<> struct sprite::rewrite< CTOR >
Rewrites a node to a CTOR node.
The tag member holds the static constructor identifier, which is a value greater than or equal to CTOR. The tag is set to that. The id is set to the dynamic constructor identifer (which is assigned at program load time).
Definition at line 60 of file rewrite.hpp.
Member Function Documentation
template<typename Enum> void sprite::rewrite< CTOR >::operator() (Node & node, Enum tag, size_t id, size_t arity, NodePtr * args) const [inline]
Note: This function _claims_ ownership of the pointer and will delete it with delete[].
Definition at line 88 of file rewrite.hpp.
References sprite::Node::_payload(), sprite::Node::destroy_payload(), sprite::Node::m_arity, sprite::Node::m_id, sprite::Node::m_tag, and sprite::make_ctor_tag().
The documentation for this struct was generated from the following file:
sprite/rewrite.hpp