sprite::Node Struct Reference
An expression node.
#include <node.hpp>
Public Types
typedef boost::iterator_range< NodePtr * > range_type
A range of child pointers; somewhat analogous to pair(Node**,Node**).
typedef boost::iterator_range< NodePtr const * > const_range_type
A non-mutable range of children.
Public Member Functions
uint32 refcount () const
Returns the reference count.
TagValue tag () const
Returns the tag member.
uint32 id () const
Returns the id member.
uint32 arity () const
Returns the arity member.
NodePtr clone ()
Clone this node, including its payload.
void * _payload ()
Get the raw address of the payload region.
void const * _payload () const
range_type iter ()
Returns a mutable range containing the children of this node.
const_range_type iter () const
Returns a constant range containing the children of this node.
NodePtr & operator[] (size_t i)
Returns the child at position i. The first child is at index 0.
NodePtr const & operator[] (size_t i) const
Returns the child at position i. The first child is at index 0.
size_t position (NodePtr const &child) const
Returns the position of the given child.
Friends
struct visitors::Clone
struct Node_
struct rewrite
void intrusive_ptr_add_ref (Node *node)
Increment the refcount. Do not call this directly.
void intrusive_ptr_release (Node *node)
Decrement the refcount. Do not call this directly.
Detailed Description
An expression node.
The subject of computations in this system. Expressions are graphs made up of Node(p.) instances, and computations are changes to the graph that come about by rewriting nodes.
Every node has a fixed region consisting of its refcount, tag, id, and arity, and a variable region called the payload. This class defines only the fixed region. A complete node is an instance of Node_<Payload> for some Payload type. The node is a discriminated union, where the tag member determines the type of the payload contents. In certain cases, the arity is also used to determine the payload type. The possible payload types are defined in the payloads namespace.
For constructor nodes, the tag member encodes the identity of the constructor. The constructors for any given type are numbered sequentially beginning at OPER.
For operation nodes, the id member identifies which operation is used. The id is an index into a corresponding table in the program, which can be used to get information about the program entity, such as its name (label) or implementation (H) function. For choice nodes, the id is the choice identifier.
The arity is stored within a node simply as an optimization. This prevents us having to repeatedly look up the arity in the program description.
Data members that are either unused or that can have only one possible value for a given tag are not updated during a rewrite. For instance, a node with the tag FAIL (representing a failed computation) will not have meaningful values for id or arity. Less obvious, perhaps, is that a node with the tag CHOICE, will have no meaningful value for arity, even though it always has exactly two children. In general, it should be obvious from the tag and the above characterization which data members have meaningful values.
Nodes are managed through intrusive reference counting. The smart pointer type NodePtr(p.) is used throughout this program to refer to nodes. It manages the refcount member and, when the count drops to zero, deletes the Node(p.) instance. All memory allocation for nodes is pooled.
Definition at line 78 of file node.hpp.
Member Function Documentation
NodePtr sprite::Node::clone () [inline]
Clone this node, including its payload.
This will produce a complete node, i.e., an instance of Node_<Payload>.
Definition at line 219 of file node_impl.hpp.
References sprite::visit().
Referenced by sprite::pull_tab().
size_t sprite::Node::position (NodePtr const & child) const [inline]
Returns the position of the given child.
Precondition: child is node[i] for some i.
Definition at line 193 of file node_impl.hpp.
References sprite::visit().
Referenced by sprite::pull_tab().
The documentation for this struct was generated from the following files:
sprite/node.hpp
sprite/detail/node_impl.hpp