sprite/visit.hpp File Reference
Implements visitation for nodes.
#include `sprite/node.hpp`
Namespaces
namespace sprite
namespace sprite::detail
Classes
struct sprite::detail::UnwrapConst< Visitor >
struct sprite::detail::BinaryVisitor< Visitor >
Defines
#define SPRITE_visit(tag, arity) visitor(static_cast<meta::NodeOf<tag,arity>::type const &>(node));
Functions
template<typename Visitor> Visitor::result_type visit (Visitor const &visitor, Node const &node)
Unary visitation; calls visitor((Type)(node)).
template<typename Visitor> Visitor::result_type visit (Visitor const &visitor, Node &node)
Non-const form of visitation.
template<typename Visitor> Visitor::result_type visit (Visitor const &visitor, Node const &lhs, Node const &rhs)
Binary visitation; calls visitor((TypeLhs)(lhs), (TypeRhs)(rhs)).
template<typename Visitor> Visitor::result_type visit (Visitor const &visitor, Node &lhs, Node &rhs)
Non-const form of binary visitation.
Detailed Description
Implements visitation for nodes.
Definition in file visit.hpp.
Function Documentation
template<typename Visitor> Visitor::result_type visit (Visitor const & visitor, Node const & lhs, Node const & rhs) [inline]
Binary visitation; calls visitor((TypeLhs)(lhs), (TypeRhs)(rhs)).
Determines the type of each node, then calls the visitor with both nodes cast to those types.
Rather than support all four possible overloads related to the const qualifier on Node(p.) arguments, just support the cases where both are qualified or neither one is.
Definition at line 143 of file visit.hpp.
template<typename Visitor> Visitor::result_type visit (Visitor const & visitor, Node const & node) [inline]
Unary visitation; calls visitor((Type)(node)).
Determines the type of the node, based on its tag and arity, then calls the visitor with the node cast to that type.
Definition at line 18 of file visit.hpp.
References sprite::Node::arity(), and sprite::Node::tag().
Referenced by sprite::Node::clone(), sprite::Node::iter(), sprite::Node::operator[](), and sprite::Node::position().