SUBMODULES=
INSTALL_DIR= # no installation from this directory.
# mpsgc.c is not compiled.  The selected collector is gc/wdgc.cpp, included
# from memory.cpp.
SRCS := $(wildcard *.cpp)
include Make.include

