-- A program for unit_setfunctions_bugs.py (issue #121).  Generated by the
-- differential harness (class FS-S, seed 83, depth 3, ops 3, free depth 2).
-- The strict constraint x16 =:= m13 of the capsule equates a variable of
-- the capsule with a variable of the goal reached through the box of a
-- captured argument; the Python backend built the pair with the guard and
-- read no id from it.
module PyFingerprintNone where
import Control.SetFunctions

data Nat = Z | S Nat
  deriving (Eq, Ord, Show)

asBool :: Bool -> Bool
asBool v = v

asList :: [Bool] -> [Bool]
asList v = v

asMaybe :: Maybe Bool -> Maybe Bool
asMaybe v = v

asNat :: Nat -> Nat
asNat v = v

bndNat :: Nat -> Bool
bndNat Z = True
bndNat (S Z) = True
bndNat (S (S Z)) = True

f1 :: (Bool, Nat) -> Bool -> (Bool, Nat)
f1 (b3, Z) False = (True, S Z)
f1 (b3, Z) True = (Z =:<= asNat Z) &> (True, S Z)
f1 (b3, S n5) b2 = (((Just False ? failed) =:= asMaybe (Just True)) &> (let x6 free in (bndNat x6 &> ((x6 =:= asNat n5) &> (True, S Z))))) ? (b3, (n5 ? S (S Z)))

f2 :: [Bool] -> Maybe Bool -> (Bool, Nat)
f2 l7 Nothing = f1 ((let x9 free in f1 failed x9) ? (False, Z)) (((Z ? S (S Z)) =:= asNat Z) &> True)
f2 l7 (Just b10) = failed

f3 :: (Bool, Nat) -> (Bool, Nat) -> Maybe Bool -> [Bool]
f3 p11 p12 m13 = sortValues (set2 (\a14 a15 -> asBool (let x16 free in ((x16 =:= asMaybe m13) &> False))) (asList (let x17 free in ((x17 =:= asBool False) &> []))) (asMaybe (Nothing ? Just True))) ? []

goal :: (Bool, Maybe Bool, [Bool])
goal = let x18, x19 free in (x18, x19, f3 (f2 failed Nothing) failed ((Z =:<= asNat (Z ? Z)) &> x19))

-- The same cause through a value binding (found in review).  The variable
-- of the goal, y, of the builtin type Int, is narrowed inside the capsule
-- through the box of the captured argument.  The Python backend built the
-- pair of the value binding with the guard, read no id from it, and
-- dropped the binding: the comparison then suspended.
k2 :: Int -> Bool
k2 m = (m =:= 1) &> (m == 1)

valueBinding :: (Int, [Bool])
valueBinding = let y free in (y, sortValues (set1 k2 y))
