-- A program for unit_setfunctions_bugs.py (issue #120).  Generated by the
-- differential harness (class FS-S, seed 2, depth 3, ops 3, free depth 2).
-- The set function of the third component returns values with a free
-- variable, which sortValues compares; the Python backend asserted in
-- get_generator on the copy of the variable in the value.
module PyGeneratorAssert where
import Control.SetFunctions

data Nat = Z | S Nat
  deriving (Eq, Ord, Show)

asBool :: Bool -> Bool
asBool v = v

asList :: [Bool] -> [Bool]
asList v = v

asMaybe :: Maybe Bool -> Maybe Bool
asMaybe v = v

asNat :: Nat -> Nat
asNat v = v

asPair :: (Bool, Nat) -> (Bool, Nat)
asPair v = v

f1 :: [Bool] -> Bool
f1 l1 = let b3, l4 free in (((b3 : l4) =:<= asList ((l1 ? [True, False]) ? (failed : l1))) &> (False ? b3))

f2 :: Maybe Bool -> Nat
f2 Nothing = ((failed ? S (S Z)) ? S (S Z)) ? (((Just True =:<= asMaybe failed) &> S (S Z)) ? (let n6 free in ((S (S n6) =:<= asNat (S (S Z))) &> n6)))
f2 (Just b7) = S Z

f3 :: Maybe Bool -> Nat
f3 Nothing = (let b10 free in ((Just b10 =:<= asMaybe Nothing) &> ((False =:<= asBool b10) &> Z))) ? Z
f3 (Just False) = Z
f3 (Just True) = f2 Nothing

goal :: (Nat, [(Bool, Nat)], [Bool])
goal = let d12 = (False ? True) in (f3 (Just True), sortValues (set1 (\a13 -> asPair (((True, Z) =:= asPair ((True, S Z) ? (False, Z))) &> (d12, Z))) (asBool d12)), sortValues (set1 f1 (asList (let x15 free in [x15]))))
