# Disable code related to LLVM.  There is no LLVM backend yet.
SUBMODULES =
# Disable the gc module, too.
SRCS := fingerprint.cpp

SHLIB := libsprite
RELATIVE_INSTALL_DIR := lib

include Make.include

