#!/bin/bash

set -e

if [ "$#" != "1" ]; then
  echo "Usage: compileState curryfile"
  exit 1
fi

if [ -z "${SPRITE_HOME:-}" ]; then
  SPRITE_HOME=`(cd "\`dirname \"$0\"\`"/.. > /dev/null ; pwd)`
fi
export SPRITE_HOME

if [ -n "$CURRYPATH" ]; then
  CURRYPATH="$SPRITE_HOME/lib:$CURRYPATH"
else
  CURRYPATH="$SPRITE_HOME/lib"
fi
export CURRYPATH

pakcs -q -s $1

